[2023-03-28T22:36:14.063+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:36:14.092+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:36:14.094+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:36:14.096+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T22:36:14.097+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:36:14.136+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_subcellular_locations> on 2023-03-27 00:00:00+00:00
[2023-03-28T22:36:14.145+0000] {standard_task_runner.py:55} INFO - Started process 1133 to run task
[2023-03-28T22:36:14.156+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_subcellular_locations', 'scheduled__2023-03-27T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmpczvp3s5f']
[2023-03-28T22:36:14.158+0000] {standard_task_runner.py:83} INFO - Job 98: Subtask write_subcellular_locations
[2023-03-28T22:36:14.348+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [running]> on host 147865a62ab8
[2023-03-28T22:36:14.612+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_subcellular_locations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T00:00:00+00:00
[2023-03-28T22:36:14.616+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 151, in write_subcellular_locations
    if isinstance(location.get("location"), list):
AttributeError: 'NoneType' object has no attribute 'get'
[2023-03-28T22:36:14.657+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=etl_uniprot_Q9Y261, task_id=write_subcellular_locations, execution_date=20230327T000000, start_date=20230328T223614, end_date=20230328T223614
[2023-03-28T22:36:14.687+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 98 for task write_subcellular_locations ('NoneType' object has no attribute 'get'; 1133)
[2023-03-28T22:36:14.729+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T22:36:14.783+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-28T22:39:28.196+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:39:28.216+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:39:28.218+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:39:28.219+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T22:39:28.219+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:39:28.252+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_subcellular_locations> on 2023-03-27 00:00:00+00:00
[2023-03-28T22:39:28.259+0000] {standard_task_runner.py:55} INFO - Started process 1329 to run task
[2023-03-28T22:39:28.266+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_subcellular_locations', 'scheduled__2023-03-27T00:00:00+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmpv0mrzqzh']
[2023-03-28T22:39:28.267+0000] {standard_task_runner.py:83} INFO - Job 118: Subtask write_subcellular_locations
[2023-03-28T22:39:28.460+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [running]> on host 147865a62ab8
[2023-03-28T22:39:28.634+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_subcellular_locations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T00:00:00+00:00
[2023-03-28T22:39:28.638+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 151, in write_subcellular_locations
    if isinstance(location.get("location"), list):
AttributeError: 'NoneType' object has no attribute 'get'
[2023-03-28T22:39:28.668+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=etl_uniprot_Q9Y261, task_id=write_subcellular_locations, execution_date=20230327T000000, start_date=20230328T223928, end_date=20230328T223928
[2023-03-28T22:39:28.701+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 118 for task write_subcellular_locations ('NoneType' object has no attribute 'get'; 1329)
[2023-03-28T22:39:28.718+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T22:39:28.774+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-28T22:42:13.910+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:42:13.950+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:42:13.951+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:42:13.953+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T22:42:13.954+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:42:14.009+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_subcellular_locations> on 2023-03-27 00:00:00+00:00
[2023-03-28T22:42:14.020+0000] {standard_task_runner.py:55} INFO - Started process 1547 to run task
[2023-03-28T22:42:14.045+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_subcellular_locations', 'scheduled__2023-03-27T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmpxxj9lu5x']
[2023-03-28T22:42:14.047+0000] {standard_task_runner.py:83} INFO - Job 152: Subtask write_subcellular_locations
[2023-03-28T22:42:14.243+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [running]> on host 147865a62ab8
[2023-03-28T22:42:14.562+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_subcellular_locations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T00:00:00+00:00
[2023-03-28T22:42:14.570+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/decorators/base.py", line 217, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/uniprot_Q9Y261/main.py", line 151, in write_subcellular_locations
    if isinstance(location.get("location"), list):
AttributeError: 'NoneType' object has no attribute 'get'
[2023-03-28T22:42:14.615+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=etl_uniprot_Q9Y261, task_id=write_subcellular_locations, execution_date=20230327T000000, start_date=20230328T224213, end_date=20230328T224214
[2023-03-28T22:42:14.650+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 152 for task write_subcellular_locations ('NoneType' object has no attribute 'get'; 1547)
[2023-03-28T22:42:14.692+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-28T22:42:14.760+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-28T22:46:44.016+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:46:44.067+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [queued]>
[2023-03-28T22:46:44.068+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:46:44.072+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-03-28T22:46:44.078+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-28T22:46:44.144+0000] {taskinstance.py:1303} INFO - Executing <Task(_PythonDecoratedOperator): write_subcellular_locations> on 2023-03-27 00:00:00+00:00
[2023-03-28T22:46:44.166+0000] {standard_task_runner.py:55} INFO - Started process 1789 to run task
[2023-03-28T22:46:44.192+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_uniprot_Q9Y261', 'write_subcellular_locations', 'scheduled__2023-03-27T00:00:00+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/uniprot_Q9Y261/main.py', '--cfg-path', '/tmp/tmp60o685dd']
[2023-03-28T22:46:44.201+0000] {standard_task_runner.py:83} INFO - Job 167: Subtask write_subcellular_locations
[2023-03-28T22:46:44.394+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_uniprot_Q9Y261.write_subcellular_locations scheduled__2023-03-27T00:00:00+00:00 [running]> on host 147865a62ab8
[2023-03-28T22:46:44.656+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_uniprot_Q9Y261
AIRFLOW_CTX_TASK_ID=write_subcellular_locations
AIRFLOW_CTX_EXECUTION_DATE=2023-03-27T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-27T00:00:00+00:00
[2023-03-28T22:46:44.663+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-28T22:46:44.698+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=etl_uniprot_Q9Y261, task_id=write_subcellular_locations, execution_date=20230327T000000, start_date=20230328T224644, end_date=20230328T224644
[2023-03-28T22:46:44.766+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-28T22:46:44.950+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
